server:
  port: 8787
  servlet:

    jsp:
      init-parameters:
        development: true
    context-path: /cmfz

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity
mvc:
  view:
    prefix: /
    suffer: .jsp